trigger:
- master
# - develop

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Nothing to do yet'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      git checkout $(Build.SourceBranchName)
      git remote add heroku https://heroku:$(pat)@git.heroku.com/boomers-app.git
      git push heroku $(Build.SourceBranchName)