trigger:
- master
- develop

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Nothing to do yet'

- task: PushToHeroku@0
  inputs:
    ApiKey: 'f0e0557f-070e-4027-9e36-c259ce2ed240'
    AppName: 'boomers-app'
    PushRoot: '.'